site_name: Detribes documentation
nav:
  - index.md
  - UserGuide.md
  - Lightpaper:
      - Overview: Lightpaper/Overview.md
      - Architecutre: Lightpaper/Architecture.md
      - Detribe: Lightpaper/Detribe.md
theme:
  name: material
